services:
  - docker

jobs:
  include:
    - name: Detect Secrets
      cache: false
      before_install:
        - pip install detect-secrets
      script:
        - detect-secrets scan --update .secrets.baseline
        - detect-secrets audit --report --fail-on-unaudited --fail-on-live --fail-on-audited-real --omit-instructions .secrets.baseline
